# 一、tf.shape、
# 二、tf.reshape、
# 三、tf.cast 、
# 四、tf.convert_to_tensor、
# 五、tf.expand_dims、
# 六、tf.squeeze
它们在处理张量形状、重构结构和类型转换时非常常用。

---
## 🔹 一、tf.shape() —— 获取张量的形状
✅ 功能：返回张量的 动态形状（即运行时 shape）

In [ ]:
import tensorflow as tf

x = tf.constant([[1, 2, 3], [4, 5, 6]]) # 创建不可变张量
shape = tf.shape(x)
print(shape)  # 输出: [2 3] --> 2行 3列


### 📌 特点：
| 特性         | 说明           |
| ---------- | ------------ |
| 返回的是张量     | 而非 Python 元组 |
| 支持动态 shape | 可用于计算图中作为输入  |
✅ 和 x.shape 不同，后者返回静态 shape（Python 对象）

---

## 🔹 二、tf.reshape() —— 改变张量的形状（不改变数据）
✅ 功能：重新排列张量结构，只要总元素个数不变

In [ ]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
reshaped = tf.reshape(x, [3, 2])  --> 2行3列 -->3行2列 
print(reshaped)
# 输出:
# [[1 2]
#  [3 4]
#  [5 6]]

### 📌 特点：
| 特性       | 说明               |
| -------- | ---------------- |
| 数据不会改变   | 只是“换个形状”         |
| 支持自动推导维度 | 用 `-1` 自动计算该维度大小 |

### 💡 示例：自动推导维度

In [ ]:
x = tf.constant([1, 2, 3, 4, 5, 6])
x_reshaped = tf.reshape(x, [-1, 2])

print(x_reshaped)  # [[1, 2], [3, 4], [5, 6]]

❗ reshape 失败会报错，比如维度不一致

## 🔹 三、tf.cast() —— 改变张量的数据类型
✅ 功能：将张量从一种 dtype 转换为另一种

In [ ]:
x = tf.constant([1.8, 2.3, 3.9])
x_int = tf.cast(x, tf.int32)
print(x_int)  # 输出: [1 2 3]（直接截断）

### 📌 常见类型：
tf.float32, tf.float64 \
tf.int32, tf.int64\
tf.bool

### 💡 示例：将整数转为布尔类型

In [ ]:
x = tf.constant([0, 1, 2])
x_bool = tf.cast(x, tf.bool)
print(x_bool)  # [False True True]

### ✅ 三者对比总结表：
| 函数             | 功能        | 输入            | 输出     | 常用场景         |
| -------------- | --------- | ------------- | ------ | ------------ |
| `tf.shape()`   | 获取张量运行时形状 | 张量            | 张量（整数） | 动态 shape 处理  |
| `tf.reshape()` | 重新定义形状    | 张量 + 新 shape  | 新张量    | 数据预处理、调整输入维度 |
| `tf.cast()`    | 类型转换      | 张量 + 目标 dtype | 新张量    | 标签转换、归一化后还原等 |

### 🎯 实战例子
一个典型的例子，把图像（像素）输入数据归一化并转换为模型所需 shape：

In [ ]:
def preprocess_image(image):
    image = tf.cast(image, tf.float32)        # 转成 float32
    image = tf.reshape(image, [28, 28, 1])     # 变为 [高, 宽, 通道]
    image = image / 255.0                      # 归一化
    return image


# 🔹四、tf.convert_to_tensor
## 一、作用
用于将多种类型的输入（如 Python 的 list、NumPy 数组、标量、tf.Tensor 本身等）统一转换为 tf.Tensor 类型。

它是 `TensorFlow` 的核心函数之一，很多 `API`（例如 tf.constant、tf.Variable）底层都调用了它。

---
## 二、函数签名

In [ ]:
tf.convert_to_tensor(
    value, 
    dtype=None, 
    dtype_hint=None, 
    name=None
)


| 参数名 | 说明 |
| :--- | :--- |
| **value** | 要转换的数据，可以是：<br>• Python 的基本类型：`int`, `float`, `bool`<br>• Python 的 `list` / `tuple`<br>• NumPy 数组<br>• `tf.Tensor`（如果本身就是 Tensor，会直接返回，不会额外创建新的）<br>• 其他支持 Tensor 转换的对象 |
| **dtype**（可选） | 指定生成 Tensor 的数据类型，比如 `tf.float32`、`tf.int32`。<br>如果不指定，TensorFlow 会自动推断。 |
| **dtype_hint**（可选） | 数据类型的“建议值”。如果 `dtype` 没有指定，TensorFlow 会优先尝试 `dtype_hint`，再进行自动推断。<br>适合在不严格要求类型时，提示系统“最好用某个 dtype”。<br>**例子**：模型推理时你传 `int` 数据，但希望保持 `float` 计算，就可以用 `dtype_hint=tf.float32`。 |
| **name**（可选） | 给生成的 Tensor 命名，主要用于图模式（graph mode）调试。 |

---

## 三、返回值

- 返回一个 `tf.Tensor` 对象。

---

## 四、使用示例
### 1. 基本用法

In [ ]:
import tensorflow as tf
import numpy as np

# 从 Python list
t1 = tf.convert_to_tensor([1, 2, 3])
print(t1)   # tf.Tensor([1 2 3], shape=(3,), dtype=int32)

# 从 NumPy 数组
arr = np.array([[1.0, 2.0], [3.0, 4.0]])
t2 = tf.convert_to_tensor(arr, dtype=tf.float32)
print(t2)
# tf.Tensor(
# [[1. 2.]
#  [3. 4.]], shape=(2, 2), dtype=float32)

# 从 Python 标量
t3 = tf.convert_to_tensor(7)
print(t3)   # tf.Tensor(7, shape=(), dtype=int32)


### 2. dtype 与 dtype_hint 区别

In [ ]:
# 指定 dtype
t4 = tf.convert_to_tensor([1, 2, 3], dtype=tf.float32)
print(t4)   # dtype=float32

# 仅使用 dtype_hint
t5 = tf.convert_to_tensor([1, 2, 3], dtype_hint=tf.float32)
print(t5)   # dtype=float32

# 如果指定 dtype，会忽略 dtype_hint
t6 = tf.convert_to_tensor([1, 2, 3], dtype=tf.int64, dtype_hint=tf.float32)
print(t6)   # dtype=int64


### 3. 避免重复创建 Tensor

In [ ]:
t = tf.constant([1, 2, 3])
t_new = tf.convert_to_tensor(t)
print(t is t_new)   # True，说明没有重复创建


### 4. 实际场景应用

- `Keras` / `TensorFlow` 模型输入时，把 numpy 或 list 转换为 Tensor。

- 数据预处理 `pipeline` 中，把 Python 对象（比如一批数值）转成 Tensor。

- 避免类型不一致，比如训练时统一转成 tf.float32。

---
## 五、和 tf.constant 的区别
| 特性            | `tf.convert_to_tensor`                    | `tf.constant`         |
| ------------- | ----------------------------------------- | --------------------- |
| 作用            | 将已有对象转换为 Tensor（不拷贝已是 Tensor 的输入）         | 创建一个新的 Tensor 常量      |
| 灵活性           | 更通用，可以输入 `Tensor`、`EagerTensor`、`NumPy` 等 | 只能从原始数据（list、numpy）创建 |
| 返回值           | Tensor                                    | Tensor（常量）            |
| 是否复制已有 Tensor | 不会                                        | 总是复制                  |

### 例子：

In [ ]:
t = tf.constant([1, 2, 3])
print(tf.convert_to_tensor(t) is t)   # True
print(tf.constant(t) is t)            # False

## 六、小结

- `tf.convert_to_tensor` 是 输入数据到 TensorFlow 的入口函数。

- 支持多种输入类型 → 统一成 `tf.Tensor`。

- `dtype` 强制类型，`dtype_hint` 给出推荐类型。

- 与 `tf.constant` 的主要区别在于是否“`复用`已有 `Tensor`”。

---

# 五、tf.expand_dims、
## 1. 作用与直觉

把张量的形状中某个位置插入一个新轴，且该轴长度为 1。
- 常见于：

   - 给图像/序列补 `batch` 维 或 通道维；

   - 为 广播(broadcasting) 做准备（例如把 (N,) 变成 (1, N) 或 (N, 1)）；

   - 让张量满足某些层/算子对 `rank` 的要求（比如 Conv2D 要求 4D：(B, H, W, C)）。

---
## 2. 函数签名

In [ ]:
tf.expand_dims(
    input,    # --> 任意 tf.Tensor（密集张量）。
    axis,     # --> 插入位置，可以为负数（从末尾数起）。取值范围是 [-(rank+1), rank]。
    name=None 
)  # --> 返回：在 axis 位置多了一个长度为 1 的维度的新张量（不复制数据，本质是视图上的形状变换）。

## 3. 形状规则与 axis 范围

设原张量 x.shape = [d0, d1, ..., d{k-1}]，rank = k。

- 允许的 axis：-(k+1) <= axis <= k

- 插入后形状：

   - 若 axis >= 0 ：[d0, ..., d{axis-1}, 1, d{axis}, ..., d{k-1}]

   - 若 axis < 0 ：把负索引换算成 `axis` = axis + (k+1) 再按上面规则插入。

- 一次只能插入一个维度；要插多个，重复调用或用 `tf.reshape`。

## 4. 常见用法示例

In [ ]:
import tensorflow as tf

x = tf.constant([1, 2, 3])     # shape: (3,)

# 4.1 在最前面插入 batch 维
xb = tf.expand_dims(x, axis=0)  # shape: (1, 3)

# 4.2 在最后插入通道维
xc = tf.expand_dims(x, axis=-1) # shape: (3, 1)

# 4.3 图像：从 (H, W, C) 升到 (1, H, W, C)
img = tf.random.uniform([224, 224, 3])
img_batched = tf.expand_dims(img, 0)   # (1, 224, 224, 3)

# 4.4 广播：构造外和/外积的形状
a = tf.range(4)             # (4,)
b = tf.range(3)             # (3,)
A = tf.expand_dims(a, 1)    # (4, 1)
B = tf.expand_dims(b, 0)    # (1, 3)
M = A + B                   # (4, 3) 逐元素广播相加

# 4.5 RNN：把 (T, F) 升到 (B, T, F)（例如单样本推理）
seq = tf.random.normal([100, 64])   # (T=100, F=64)
seq_batched = tf.expand_dims(seq, 0) # (1, 100, 64)


## 5. 与 tf.newaxis（或 None）的等价写法

在切片中使用 `tf.newaxis`（就是 None）也能插入维度：

In [ ]:
x = tf.constant([1, 2, 3])      # (3,)

x0 = x[tf.newaxis, ...]         # (1, 3)   等价于 tf.expand_dims(x, 0)
x1 = x[..., tf.newaxis]         # (3, 1)   等价于 tf.expand_dims(x, -1)

二者常用哪个纯看个人/团队风格；expand_dims 更显式，在函数式管道中更清晰。

## 6. 与 tf.reshape、tf.squeeze 的关系

- `tf.expand_dims`：只能插入长度为 1 的新维度，语义清晰，出错概率低。

- `tf.reshape`：可一次性把形状重排/插 1，灵活但更容易不小心改错整体形状。

- `tf.squeeze`：相反操作，移除长度为 1 的维度。

In [ ]:
x = tf.constant([[1, 2, 3]])     # (1, 3)
y = tf.squeeze(x, axis=0)        # (3,)
z = tf.expand_dims(y, axis=0)    # (1, 3)  回到原状


实战建议：只需要加一个 1 维时用 expand_dims；需要一次加/改多个维时再考虑 reshape。

---
## 7. 典型场景清单

- 补 `Batch` 维：(H, W, C) -> (1, H, W, C)，或 (T, F) -> (1, T, F)
（单样本推理/可视化时很常见）

- 补通道维：灰度图 (H, W) -> (H, W, 1)，便于送入 `Conv2D`

- 广播对齐：向量加矩阵/构造外和/外积 \
`a`: (N,) -> (N, 1) 与 `b`: (M,) -> (1, M)，得到 (N, M)

- 对齐层的 `rank` 要求：某些 API 要求固定 rank（如 3D/4D/5D）

---
## 8. 性能与梯度

- 零拷贝的形状变换（视图/元数据层面的改变），几乎不增加内存开销；

- 可微：反向传播会透明地穿过该操作，不影响梯度计算。

---
## 9. 常见坑与排查

- 1.`axis` 越界

   - 错误示例：对 1D 张量设 axis=2（允许范围是 [-2, 1]）。

   - 处理：先 print(x.shape, tf.rank(x))；必要时把负轴换算为正轴。

- 2.一次插多个维度

   - `expand_dims` 一次只插一个维度；连用多次或改用 `reshape`：

In [ ]:
x = tf.random.normal([8, 16])       # (8, 16)
y = tf.reshape(x, [1, 8, 16, 1])    # (1, 8, 16, 1)


- 3.和 `tf.newaxis` 混用导致读写不一致

   - 团队风格统一：要么都用函数式 `tf.expand_dims`，要么都用切片式 `tf.newaxis`。

- 4.模型输入 rank 不符

   - `Keras` 的 Conv2D 期望 4D (B,H,W,C)；若只有 (H,W,C)，需要先 expand_dims(x, 0)。

---
## 10. 迷你速查表
| 目标           | 代码                                           | 说明                     |
| ------------ | -------------------------------------------- | ---------------------- |
| 补 batch 维到前面 | `x = tf.expand_dims(x, 0)`                   | `(H,W,C) → (1,H,W,C)`  |
| 补通道维到最后      | `x = tf.expand_dims(x, -1)`                  | `(H,W) → (H,W,1)`      |
| 行向量化         | `x = tf.expand_dims(x, 0)`                   | `(N,) → (1,N)`         |
| 列向量化         | `x = tf.expand_dims(x, -1)`                  | `(N,) → (N,1)`         |
| 外和/外积准备      | `A = a[:, tf.newaxis]; B = b[tf.newaxis, :]` | `(N,1)` 与 `(1,M)`      |
| 末尾插入         | `x = tf.expand_dims(x, tf.rank(x))`          | 等价于 `axis = -1`        |
| 最前插入         | `x = tf.expand_dims(x, 0)`                   | 等价于 `axis = -(rank+1)` |


# 六、tf.squeeze
## 1. 作用

`移除`张量中所有（或指定位置的）长度为 1 的维度，也叫 `“压缩维度”`。

在深度学习里很常见，比如：

 - 模型预测结果 `(N, 1)` → 转为 `(N,)`；

 - 灰度图 `(H, W, 1)` → 转为 `(H, W)`；

 - 临时 `batch` 维 (`1, H, W, C)` → 转为 `(H, W, C)`。

## 2. 函数签名

In [ ]:
tf.squeeze(
    input,     # 待处理的张量。
    axis=None, # （可选）：要移除的 特定维度索引（或多个索引 list/tuple）。
               #  如果 为 None（默认）：移除所有长度为 1 的维度。
               #  如果指定，则只移除这些位置的维度，而且必须保证这些维度长度为 1，否则报错。
    name=None
)
 # --> 一个移除了指定维度的张量，数据不变，只是形状变化（零拷贝操作）

## 3. 基本示例

In [ ]:
import tensorflow as tf

# 原始张量 shape (1, 3, 1, 5)
x = tf.zeros([1, 3, 1, 5])

# 3.1 默认：移除所有长度为1的维度
y1 = tf.squeeze(x)
print(y1.shape)   # (3, 5)

# 3.2 只移除 axis=0
y2 = tf.squeeze(x, axis=0)
print(y2.shape)   # (3, 1, 5)

# 3.3 移除多个维度
y3 = tf.squeeze(x, axis=[0, 2])
print(y3.shape)   # (3, 5)

# 3.4 错误示例：axis 指定的维度长度 ≠ 1
try:
    y4 = tf.squeeze(x, axis=1)   # 第1维长度是3，不是1
except Exception as e:
    print("错误:", e)


### 4. 与 tf.expand_dims 的关系

- `expand_dims`：在指定位置 增加 一个维度，长度=1。

- `squeeze`：在指定位置 移除 一个维度，前提是长度=1。

例子：

In [ ]:
x = tf.constant([[1, 2, 3]])   # (1, 3)

y = tf.squeeze(x)              # (3,)
z = tf.expand_dims(y, axis=0)  # (1, 3)，回到原状


### 5.与 reshape 的区别

- `tf.squeeze`：只能移除长度为 1 的维度，语义更清晰，出错概率小。

- `tf.reshape`：可以任意重塑，但更灵活也更危险。\
等价写法：

In [ ]:
x = tf.zeros([1, 3, 1])
y1 = tf.squeeze(x)               # (3,)
y2 = tf.reshape(x, [3])          # (3,)

建议：去 1 维度 → 用 squeeze，更直观。

## 6. 常见坑

- 1、错误的 `axis` 指定

   - 必须是长度为 1 的维度，否则报错。

   - 解决：print(x.shape) 或 tf.rank(x) 确认形状。

- 2、 批量维意外被挤掉

   - 有时 `squeeze` 会去掉 `batch=1` 的维度，但训练/预测需要保留。

   - 解决：用 `axis` 精确指定要移除的维度。

- 3、 过度依赖自动 `squeeze`

   - 某些 API（如 Keras）可能自动返回 `(batch_size, 1)`，你需要手动 `squeeze`。
 
---

## 7. 速查表
| 输入形状             | 代码                           | 输出形状          | 说明           |
| ---------------- | ---------------------------- | ------------- | ------------ |
| `(1, 28, 28, 1)` | `tf.squeeze(x)`              | `(28, 28)`    | 去掉所有 1       |
| `(1, 28, 28, 1)` | `tf.squeeze(x, axis=0)`      | `(28, 28, 1)` | 只去掉 batch 维  |
| `(1, 28, 28, 1)` | `tf.squeeze(x, axis=[0, 3])` | `(28, 28)`    | 去掉 batch 和通道 |
| `(N, 1)`         | `tf.squeeze(x, axis=1)`      | `(N,)`        | 常见模型输出处理     |

## ✅ 小结：

 - `tf.squeeze` 是 “去掉多余 1 维” 的函数。

 - 默认去掉所有 1 维，也可以精确指定。

 - 常用于模型输出、图像灰度通道、广播前后处理。

---

# 张量的索引与修改

 - `TF` 的张量是 `不可变的`，所以不能直接 x[0,0] = 9。
 - 要用 `tf.tensor_scatter_nd_update` 或 `tf.Variable`。

In [ ]:
x = tf.Variable([[1, 2], [3, 4]])

# 修改单元素
x = tf.tensor_scatter_nd_update(x, [[0, 1]], [9])
print(x.numpy())   # [[1, 9], [3, 4]]

# 修改多元素
x = tf.tensor_scatter_nd_update(x, [[1, 0], [1, 1]], [7, 8])
print(x.numpy())   # [[1, 9], [7, 8]]


# 索引 & 切片速查表
| 语法                         | 作用         | 例子                       |
| -------------------------- | ---------- | ------------------------ |
| `x[i]`                     | 取第 i 行     | `x[0] → 第一行`             |
| `x[i, j]`                  | 取第 i 行 j 列 | `x[2,1] → 第3行第2列`        |
| `x[start:end]`             | 切片         | `x[0:2] → 前两行`           |
| `x[:, i]`                  | 取某列        | `x[:,1] → 第二列`           |
| `x[::step]`                | 步长切片       | `x[::2] → 每隔一行取一行`       |
| `x[::-1]`                  | 反转         | `x[::-1] → 倒序`           |
| `x[tf.newaxis, :]`         | 扩展维度       | `(N,) → (1,N)`           |
| `tf.boolean_mask(x, mask)` | 布尔索引       | `[1,2,3,4][x>2] → [3,4]` |
| `tf.gather(x, idx)`        | 按索引列表取值    | `idx=[0,2]` → 取第0,2个     |

## ✅ 小结：

- `TF` 索引和 `NumPy` 非常接近，但修改元素要用 `Variable` 或 `scatter` 操作。

- 常用方法：`基础索引` + `tf.newaxis` + `tf.gather` + `tf.boolean_mask`。